// ============================================================
// Voto Seguro 2026 — Datos Electorales Reales JNE
// Fuente: https://votoinformado.jne.gob.pe (Elecciones Generales 2026)
// Última actualización: Febrero 2026
// Logos: https://sroppublico.jne.gob.pe/Consulta/Simbolo/GetSimbolo/{id}
// Fotos: https://mpesije.jne.gob.pe/apidocs/{uuid}.jpg
// ============================================================

import type {
  OrganizacionPolitica,
  ListaElectoral,
  DatosSimulador,
} from "./types";

// Base URLs de APIs del JNE
const JNE_LOGO_BASE = "https://sroppublico.jne.gob.pe/Consulta/Simbolo/GetSimbolo";
const JNE_FOTO_BASE = "https://mpesije.jne.gob.pe/apidocs";

// --- Organizaciones Políticas (datos reales JNE 2026) ---
// Orden alfabético según aparece en el portal JNE
export const ORGANIZACIONES: OrganizacionPolitica[] = [
  {
    id: 1,
    nombre: "AHORA NACION - AN",
    sigla: "AN",
    colorPrimario: "#C8102E",
    colorSecundario: "#FFFFFF",
    logoUrl: `${JNE_LOGO_BASE}/2980`,
    numeroLista: 1,
  },
  {
    id: 2,
    nombre: "ALIANZA ELECTORAL VENCEREMOS",
    sigla: "AEV",
    colorPrimario: "#228B22",
    colorSecundario: "#FFFFFF",
    logoUrl: `${JNE_LOGO_BASE}/3025`,
    numeroLista: 2,
  },
  {
    id: 3,
    nombre: "ALIANZA PARA EL PROGRESO",
    sigla: "APP",
    colorPrimario: "#0047AB",
    colorSecundario: "#FFD700",
    logoUrl: `${JNE_LOGO_BASE}/1257`,
    numeroLista: 3,
  },
  {
    id: 4,
    nombre: "AVANZA PAIS - PARTIDO DE INTEGRACION SOCIAL",
    sigla: "AP",
    colorPrimario: "#003DA5",
    colorSecundario: "#FFFFFF",
    logoUrl: `${JNE_LOGO_BASE}/2173`,
    numeroLista: 4,
  },
  {
    id: 5,
    nombre: "FE EN EL PERU",
    sigla: "FEP",
    colorPrimario: "#006400",
    colorSecundario: "#FFFFFF",
    logoUrl: `${JNE_LOGO_BASE}/2898`,
    numeroLista: 5,
  },
  {
    id: 6,
    nombre: "FUERZA POPULAR",
    sigla: "FP",
    colorPrimario: "#FF8C00",
    colorSecundario: "#FFFFFF",
    logoUrl: `${JNE_LOGO_BASE}/1366`,
    numeroLista: 6,
  },
  {
    id: 7,
    nombre: "FUERZA Y LIBERTAD",
    sigla: "FYL",
    colorPrimario: "#8B0000",
    colorSecundario: "#FFFFFF",
    logoUrl: `${JNE_LOGO_BASE}/3024`,
    numeroLista: 7,
  },
  {
    id: 8,
    nombre: "JUNTOS POR EL PERU",
    sigla: "JPP",
    colorPrimario: "#228B22",
    colorSecundario: "#FFFFFF",
    logoUrl: `${JNE_LOGO_BASE}/1264`,
    numeroLista: 8,
  },
  {
    id: 9,
    nombre: "LIBERTAD POPULAR",
    sigla: "LP",
    colorPrimario: "#4169E1",
    colorSecundario: "#FFFFFF",
    logoUrl: `${JNE_LOGO_BASE}/2933`,
    numeroLista: 9,
  },
  {
    id: 10,
    nombre: "PARTIDO APRISTA PERUANO",
    sigla: "PAP",
    colorPrimario: "#CC0000",
    colorSecundario: "#FFFFFF",
    logoUrl: `${JNE_LOGO_BASE}/2930`,
    numeroLista: 10,
  },
  {
    id: 11,
    nombre: "PARTIDO CIVICO OBRAS",
    sigla: "PCO",
    colorPrimario: "#FF6600",
    colorSecundario: "#FFFFFF",
    logoUrl: `${JNE_LOGO_BASE}/2941`,
    numeroLista: 11,
  },
  {
    id: 12,
    nombre: "PARTIDO DE LOS TRABAJADORES Y EMPRENDEDORES PTE - PERU",
    sigla: "PTE",
    colorPrimario: "#8B4513",
    colorSecundario: "#FFFFFF",
    logoUrl: `${JNE_LOGO_BASE}/2939`,
    numeroLista: 12,
  },
  {
    id: 13,
    nombre: "PARTIDO DEL BUEN GOBIERNO",
    sigla: "PBG",
    colorPrimario: "#006400",
    colorSecundario: "#FFFFFF",
    logoUrl: `${JNE_LOGO_BASE}/2961`,
    numeroLista: 13,
  },
  {
    id: 14,
    nombre: "PARTIDO DEMOCRATA UNIDO PERU",
    sigla: "PDUP",
    colorPrimario: "#003366",
    colorSecundario: "#FFFFFF",
    logoUrl: `${JNE_LOGO_BASE}/2867`,
    numeroLista: 14,
  },
  {
    id: 15,
    nombre: "PARTIDO DEMOCRATA VERDE",
    sigla: "PDV",
    colorPrimario: "#2E8B57",
    colorSecundario: "#FFFFFF",
    logoUrl: `${JNE_LOGO_BASE}/2895`,
    numeroLista: 15,
  },
  {
    id: 16,
    nombre: "PARTIDO DEMOCRATICO FEDERAL",
    sigla: "PDF",
    colorPrimario: "#000080",
    colorSecundario: "#FFFFFF",
    logoUrl: `${JNE_LOGO_BASE}/2986`,
    numeroLista: 16,
  },
  {
    id: 17,
    nombre: "PARTIDO DEMOCRATICO SOMOS PERU",
    sigla: "PDSP",
    colorPrimario: "#FF4500",
    colorSecundario: "#FFFFFF",
    logoUrl: `${JNE_LOGO_BASE}/14`,
    numeroLista: 17,
  },
  {
    id: 18,
    nombre: "PARTIDO FRENTE DE LA ESPERANZA 2021",
    sigla: "PFE",
    colorPrimario: "#4B0082",
    colorSecundario: "#FFFFFF",
    logoUrl: `${JNE_LOGO_BASE}/2857`,
    numeroLista: 18,
  },
  {
    id: 19,
    nombre: "PARTIDO MORADO",
    sigla: "PM",
    colorPrimario: "#800080",
    colorSecundario: "#FFFFFF",
    logoUrl: `${JNE_LOGO_BASE}/2840`,
    numeroLista: 19,
  },
  {
    id: 20,
    nombre: "PARTIDO PAIS PARA TODOS",
    sigla: "PPT",
    colorPrimario: "#DAA520",
    colorSecundario: "#000000",
    logoUrl: `${JNE_LOGO_BASE}/2956`,
    numeroLista: 20,
  },
  {
    id: 21,
    nombre: "PARTIDO PATRIOTICO DEL PERU",
    sigla: "PPP",
    colorPrimario: "#C8102E",
    colorSecundario: "#000000",
    logoUrl: `${JNE_LOGO_BASE}/2869`,
    numeroLista: 21,
  },
  {
    id: 22,
    nombre: "PARTIDO POLITICO COOPERACION POPULAR",
    sigla: "PPCP",
    colorPrimario: "#228B22",
    colorSecundario: "#FFFFFF",
    logoUrl: `${JNE_LOGO_BASE}/2995`,
    numeroLista: 22,
  },
  {
    id: 23,
    nombre: "PARTIDO POLITICO INTEGRIDAD DEMOCRATICA",
    sigla: "PPID",
    colorPrimario: "#1E90FF",
    colorSecundario: "#FFFFFF",
    logoUrl: `${JNE_LOGO_BASE}/2985`,
    numeroLista: 23,
  },
  {
    id: 24,
    nombre: "PARTIDO POLITICO NACIONAL PERU LIBRE",
    sigla: "PL",
    colorPrimario: "#CC0000",
    colorSecundario: "#000000",
    logoUrl: `${JNE_LOGO_BASE}/2218`,
    numeroLista: 24,
  },
  {
    id: 25,
    nombre: "PARTIDO POLITICO PERU ACCION",
    sigla: "PA",
    colorPrimario: "#006400",
    colorSecundario: "#FFFFFF",
    logoUrl: `${JNE_LOGO_BASE}/2932`,
    numeroLista: 25,
  },
  {
    id: 26,
    nombre: "PARTIDO POLITICO PERU PRIMERO",
    sigla: "PP",
    colorPrimario: "#C8102E",
    colorSecundario: "#FFFFFF",
    logoUrl: `${JNE_LOGO_BASE}/2925`,
    numeroLista: 26,
  },
  {
    id: 27,
    nombre: "PARTIDO POLITICO PRIN",
    sigla: "PRIN",
    colorPrimario: "#FF8C00",
    colorSecundario: "#000000",
    logoUrl: `${JNE_LOGO_BASE}/2921`,
    numeroLista: 27,
  },
  {
    id: 28,
    nombre: "PARTIDO SICREO",
    sigla: "SICREO",
    colorPrimario: "#4169E1",
    colorSecundario: "#FFFFFF",
    logoUrl: `${JNE_LOGO_BASE}/2935`,
    numeroLista: 28,
  },
  {
    id: 29,
    nombre: "PERU MODERNO",
    sigla: "PERMOD",
    colorPrimario: "#008080",
    colorSecundario: "#FFFFFF",
    logoUrl: `${JNE_LOGO_BASE}/2924`,
    numeroLista: 29,
  },
  {
    id: 30,
    nombre: "PODEMOS PERU",
    sigla: "PODEM",
    colorPrimario: "#FF6347",
    colorSecundario: "#FFFFFF",
    logoUrl: `${JNE_LOGO_BASE}/2731`,
    numeroLista: 30,
  },
  {
    id: 31,
    nombre: "PRIMERO LA GENTE - COMUNIDAD, ECOLOGIA, LIBERTAD Y PROGRESO",
    sigla: "PLG",
    colorPrimario: "#32CD32",
    colorSecundario: "#FFFFFF",
    logoUrl: `${JNE_LOGO_BASE}/2931`,
    numeroLista: 31,
  },
  {
    id: 32,
    nombre: "PROGRESEMOS",
    sigla: "PROG",
    colorPrimario: "#FF4500",
    colorSecundario: "#FFFFFF",
    logoUrl: `${JNE_LOGO_BASE}/2967`,
    numeroLista: 32,
  },
  {
    id: 33,
    nombre: "RENOVACION POPULAR",
    sigla: "RP",
    colorPrimario: "#4169E1",
    colorSecundario: "#FFFFFF",
    logoUrl: `${JNE_LOGO_BASE}/22`,
    numeroLista: 33,
  },
  {
    id: 34,
    nombre: "SALVEMOS AL PERU",
    sigla: "SAP",
    colorPrimario: "#8B0000",
    colorSecundario: "#FFFFFF",
    logoUrl: `${JNE_LOGO_BASE}/2927`,
    numeroLista: 34,
  },
  {
    id: 35,
    nombre: "UN CAMINO DIFERENTE",
    sigla: "UCD",
    colorPrimario: "#DAA520",
    colorSecundario: "#000000",
    logoUrl: `${JNE_LOGO_BASE}/2998`,
    numeroLista: 35,
  },
  {
    id: 36,
    nombre: "UNIDAD NACIONAL",
    sigla: "UN",
    colorPrimario: "#000080",
    colorSecundario: "#FFFFFF",
    logoUrl: `${JNE_LOGO_BASE}/3023`,
    numeroLista: 36,
  },
];

// Helper para obtener organización por nombre
function getOrg(nombre: string): OrganizacionPolitica {
  const org = ORGANIZACIONES.find((o) => o.nombre === nombre);
  if (!org) throw new Error(`Organización no encontrada: ${nombre}`);
  return org;
}

// --- Fórmulas Presidenciales Reales (JNE 2026) ---
// Fuente: https://votoinformado.jne.gob.pe/presidente-vicepresidentes
// 36 candidatos presidenciales inscritos

export const FORMULAS_PRESIDENCIALES: ListaElectoral[] = [
  {
    id: 1,
    organizacion: getOrg("AHORA NACION - AN"),
    cargo: "FORMULA_PRESIDENCIAL",
    candidatos: [],
    presidente: {
      idHojaVida: 1001,
      nombres: "PABLO ALFONSO",
      apellidoPaterno: "LOPEZ CHAU",
      apellidoMaterno: "NAVA",
      nombreCompleto: "PABLO ALFONSO LOPEZ CHAU NAVA",
      cargo: "FORMULA_PRESIDENCIAL",
      numeroCandidato: 1,
      fotoUrl: `${JNE_FOTO_BASE}/ddfa74eb-cae3-401c-a34c-35543ae83c57.jpg`,
      idOrganizacion: 1,
      estado: "INSCRITO",
      partido: "AHORA NACION - AN",
    },
  },
  {
    id: 2,
    organizacion: getOrg("ALIANZA ELECTORAL VENCEREMOS"),
    cargo: "FORMULA_PRESIDENCIAL",
    candidatos: [],
    presidente: {
      idHojaVida: 1002,
      nombres: "RONALD DARWIN",
      apellidoPaterno: "ATENCIO",
      apellidoMaterno: "SOTOMAYOR",
      nombreCompleto: "RONALD DARWIN ATENCIO SOTOMAYOR",
      cargo: "FORMULA_PRESIDENCIAL",
      numeroCandidato: 1,
      fotoUrl: `${JNE_FOTO_BASE}/bac0288d-3b21-45ac-8849-39f9177fb020.jpg`,
      idOrganizacion: 2,
      estado: "INSCRITO",
      partido: "ALIANZA ELECTORAL VENCEREMOS",
    },
  },
  {
    id: 3,
    organizacion: getOrg("ALIANZA PARA EL PROGRESO"),
    cargo: "FORMULA_PRESIDENCIAL",
    candidatos: [],
    presidente: {
      idHojaVida: 1003,
      nombres: "CESAR",
      apellidoPaterno: "ACUÑA",
      apellidoMaterno: "PERALTA",
      nombreCompleto: "CESAR ACUÑA PERALTA",
      cargo: "FORMULA_PRESIDENCIAL",
      numeroCandidato: 1,
      fotoUrl: `${JNE_FOTO_BASE}/d6fe3cac-7061-474b-8551-0aa686a54bad.jpg`,
      idOrganizacion: 3,
      estado: "INSCRITO",
      partido: "ALIANZA PARA EL PROGRESO",
    },
  },
  {
    id: 4,
    organizacion: getOrg("AVANZA PAIS - PARTIDO DE INTEGRACION SOCIAL"),
    cargo: "FORMULA_PRESIDENCIAL",
    candidatos: [],
    presidente: {
      idHojaVida: 1004,
      nombres: "JOSE DANIEL",
      apellidoPaterno: "WILLIAMS",
      apellidoMaterno: "ZAPATA",
      nombreCompleto: "JOSE DANIEL WILLIAMS ZAPATA",
      cargo: "FORMULA_PRESIDENCIAL",
      numeroCandidato: 1,
      fotoUrl: `${JNE_FOTO_BASE}/b60c471f-a6bb-4b42-a4b2-02ea38acbb0d.jpg`,
      idOrganizacion: 4,
      estado: "INSCRITO",
      partido: "AVANZA PAIS - PARTIDO DE INTEGRACION SOCIAL",
    },
  },
  {
    id: 5,
    organizacion: getOrg("FE EN EL PERU"),
    cargo: "FORMULA_PRESIDENCIAL",
    candidatos: [],
    presidente: {
      idHojaVida: 1005,
      nombres: "ALVARO GONZALO",
      apellidoPaterno: "PAZ DE LA BARRA",
      apellidoMaterno: "FREIGEIRO",
      nombreCompleto: "ALVARO GONZALO PAZ DE LA BARRA FREIGEIRO",
      cargo: "FORMULA_PRESIDENCIAL",
      numeroCandidato: 1,
      fotoUrl: `${JNE_FOTO_BASE}/251cd1c0-acc7-4338-bd8a-439ccb9238d0.jpeg`,
      idOrganizacion: 5,
      estado: "INSCRITO",
      partido: "FE EN EL PERU",
    },
  },
  {
    id: 6,
    organizacion: getOrg("FUERZA POPULAR"),
    cargo: "FORMULA_PRESIDENCIAL",
    candidatos: [],
    presidente: {
      idHojaVida: 1006,
      nombres: "KEIKO SOFIA",
      apellidoPaterno: "FUJIMORI",
      apellidoMaterno: "HIGUCHI",
      nombreCompleto: "KEIKO SOFIA FUJIMORI HIGUCHI",
      cargo: "FORMULA_PRESIDENCIAL",
      numeroCandidato: 1,
      fotoUrl: `${JNE_FOTO_BASE}/1de656b5-7593-4c60-ab7a-83d618a3d80d.jpg`,
      idOrganizacion: 6,
      estado: "INSCRITO",
      partido: "FUERZA POPULAR",
    },
  },
  {
    id: 7,
    organizacion: getOrg("FUERZA Y LIBERTAD"),
    cargo: "FORMULA_PRESIDENCIAL",
    candidatos: [],
    presidente: {
      idHojaVida: 1007,
      nombres: "FIORELLA GIANNINA",
      apellidoPaterno: "MOLINELLI",
      apellidoMaterno: "ARISTONDO",
      nombreCompleto: "FIORELLA GIANNINA MOLINELLI ARISTONDO",
      cargo: "FORMULA_PRESIDENCIAL",
      numeroCandidato: 1,
      fotoUrl: `${JNE_FOTO_BASE}/bb7c7465-9c6e-44eb-ac7d-e6cc7f872a1a.jpg`,
      idOrganizacion: 7,
      estado: "INSCRITO",
      partido: "FUERZA Y LIBERTAD",
    },
  },
  {
    id: 8,
    organizacion: getOrg("JUNTOS POR EL PERU"),
    cargo: "FORMULA_PRESIDENCIAL",
    candidatos: [],
    presidente: {
      idHojaVida: 1008,
      nombres: "ROBERTO HELBERT",
      apellidoPaterno: "SANCHEZ",
      apellidoMaterno: "PALOMINO",
      nombreCompleto: "ROBERTO HELBERT SANCHEZ PALOMINO",
      cargo: "FORMULA_PRESIDENCIAL",
      numeroCandidato: 1,
      fotoUrl: `${JNE_FOTO_BASE}/3302e45b-55c8-4979-a60b-2b11097abf1d.jpg`,
      idOrganizacion: 8,
      estado: "INSCRITO",
      partido: "JUNTOS POR EL PERU",
    },
  },
  {
    id: 9,
    organizacion: getOrg("LIBERTAD POPULAR"),
    cargo: "FORMULA_PRESIDENCIAL",
    candidatos: [],
    presidente: {
      idHojaVida: 1009,
      nombres: "RAFAEL JORGE",
      apellidoPaterno: "BELAUNDE",
      apellidoMaterno: "LLOSA",
      nombreCompleto: "RAFAEL JORGE BELAUNDE LLOSA",
      cargo: "FORMULA_PRESIDENCIAL",
      numeroCandidato: 1,
      fotoUrl: `${JNE_FOTO_BASE}/d72c4b29-e173-42b8-b40d-bdb6d01a526a.jpg`,
      idOrganizacion: 9,
      estado: "INSCRITO",
      partido: "LIBERTAD POPULAR",
    },
  },
  {
    id: 10,
    organizacion: getOrg("PARTIDO APRISTA PERUANO"),
    cargo: "FORMULA_PRESIDENCIAL",
    candidatos: [],
    presidente: {
      idHojaVida: 1010,
      nombres: "PITTER ENRIQUE",
      apellidoPaterno: "VALDERRAMA",
      apellidoMaterno: "PEÑA",
      nombreCompleto: "PITTER ENRIQUE VALDERRAMA PEÑA",
      cargo: "FORMULA_PRESIDENCIAL",
      numeroCandidato: 1,
      fotoUrl: `${JNE_FOTO_BASE}/78647f15-d5d1-4ed6-8ac6-d599e83eeea3.jpg`,
      idOrganizacion: 10,
      estado: "INSCRITO",
      partido: "PARTIDO APRISTA PERUANO",
    },
  },
  {
    id: 11,
    organizacion: getOrg("PARTIDO CIVICO OBRAS"),
    cargo: "FORMULA_PRESIDENCIAL",
    candidatos: [],
    presidente: {
      idHojaVida: 1011,
      nombres: "RICARDO PABLO",
      apellidoPaterno: "BELMONT",
      apellidoMaterno: "CASSINELLI",
      nombreCompleto: "RICARDO PABLO BELMONT CASSINELLI",
      cargo: "FORMULA_PRESIDENCIAL",
      numeroCandidato: 1,
      fotoUrl: `${JNE_FOTO_BASE}/bab206cb-b2d5-41ec-bde8-ef8cf3e0a2df.jpg`,
      idOrganizacion: 11,
      estado: "INSCRITO",
      partido: "PARTIDO CIVICO OBRAS",
    },
  },
  {
    id: 12,
    organizacion: getOrg("PARTIDO DE LOS TRABAJADORES Y EMPRENDEDORES PTE - PERU"),
    cargo: "FORMULA_PRESIDENCIAL",
    candidatos: [],
    presidente: {
      idHojaVida: 1012,
      nombres: "NAPOLEON",
      apellidoPaterno: "BECERRA",
      apellidoMaterno: "GARCIA",
      nombreCompleto: "NAPOLEON BECERRA GARCIA",
      cargo: "FORMULA_PRESIDENCIAL",
      numeroCandidato: 1,
      fotoUrl: `${JNE_FOTO_BASE}/9ae56ed5-3d0f-49ff-8bb9-0390bad71816.jpg`,
      idOrganizacion: 12,
      estado: "INSCRITO",
      partido: "PARTIDO DE LOS TRABAJADORES Y EMPRENDEDORES PTE - PERU",
    },
  },
  {
    id: 13,
    organizacion: getOrg("PARTIDO DEL BUEN GOBIERNO"),
    cargo: "FORMULA_PRESIDENCIAL",
    candidatos: [],
    presidente: {
      idHojaVida: 1013,
      nombres: "JORGE",
      apellidoPaterno: "NIETO",
      apellidoMaterno: "MONTESINOS",
      nombreCompleto: "JORGE NIETO MONTESINOS",
      cargo: "FORMULA_PRESIDENCIAL",
      numeroCandidato: 1,
      fotoUrl: `${JNE_FOTO_BASE}/12fa17db-f28f-4330-9123-88549539b538.jpg`,
      idOrganizacion: 13,
      estado: "INSCRITO",
      partido: "PARTIDO DEL BUEN GOBIERNO",
    },
  },
  {
    id: 14,
    organizacion: getOrg("PARTIDO DEMOCRATA UNIDO PERU"),
    cargo: "FORMULA_PRESIDENCIAL",
    candidatos: [],
    presidente: {
      idHojaVida: 1014,
      nombres: "CHARLIE",
      apellidoPaterno: "CARRASCO",
      apellidoMaterno: "SALAZAR",
      nombreCompleto: "CHARLIE CARRASCO SALAZAR",
      cargo: "FORMULA_PRESIDENCIAL",
      numeroCandidato: 1,
      fotoUrl: `${JNE_FOTO_BASE}/c0ae56bf-21c1-4810-890a-b25c8465bdd9.jpg`,
      idOrganizacion: 14,
      estado: "INSCRITO",
      partido: "PARTIDO DEMOCRATA UNIDO PERU",
    },
  },
  {
    id: 15,
    organizacion: getOrg("PARTIDO DEMOCRATA VERDE"),
    cargo: "FORMULA_PRESIDENCIAL",
    candidatos: [],
    presidente: {
      idHojaVida: 1015,
      nombres: "ALEX",
      apellidoPaterno: "GONZALES",
      apellidoMaterno: "CASTILLO",
      nombreCompleto: "ALEX GONZALES CASTILLO",
      cargo: "FORMULA_PRESIDENCIAL",
      numeroCandidato: 1,
      fotoUrl: `${JNE_FOTO_BASE}/cb1adeb7-7d2f-430c-ae87-519137d8edfa.jpg`,
      idOrganizacion: 15,
      estado: "INSCRITO",
      partido: "PARTIDO DEMOCRATA VERDE",
    },
  },
  {
    id: 16,
    organizacion: getOrg("PARTIDO DEMOCRATICO FEDERAL"),
    cargo: "FORMULA_PRESIDENCIAL",
    candidatos: [],
    presidente: {
      idHojaVida: 1016,
      nombres: "ARMANDO JOAQUIN",
      apellidoPaterno: "MASSE",
      apellidoMaterno: "FERNANDEZ",
      nombreCompleto: "ARMANDO JOAQUIN MASSE FERNANDEZ",
      cargo: "FORMULA_PRESIDENCIAL",
      numeroCandidato: 1,
      fotoUrl: `${JNE_FOTO_BASE}/b1d60238-c797-4cba-936e-f13de6a34cc7.jpg`,
      idOrganizacion: 16,
      estado: "INSCRITO",
      partido: "PARTIDO DEMOCRATICO FEDERAL",
    },
  },
  {
    id: 17,
    organizacion: getOrg("PARTIDO DEMOCRATICO SOMOS PERU"),
    cargo: "FORMULA_PRESIDENCIAL",
    candidatos: [],
    presidente: {
      idHojaVida: 1017,
      nombres: "GEORGE PATRICK",
      apellidoPaterno: "FORSYTH",
      apellidoMaterno: "SOMMER",
      nombreCompleto: "GEORGE PATRICK FORSYTH SOMMER",
      cargo: "FORMULA_PRESIDENCIAL",
      numeroCandidato: 1,
      fotoUrl: `${JNE_FOTO_BASE}/3e2312e1-af79-4954-abfa-a36669c1a9e9.jpg`,
      idOrganizacion: 17,
      estado: "INSCRITO",
      partido: "PARTIDO DEMOCRATICO SOMOS PERU",
    },
  },
  {
    id: 18,
    organizacion: getOrg("PARTIDO FRENTE DE LA ESPERANZA 2021"),
    cargo: "FORMULA_PRESIDENCIAL",
    candidatos: [],
    presidente: {
      idHojaVida: 1018,
      nombres: "LUIS FERNANDO",
      apellidoPaterno: "OLIVERA",
      apellidoMaterno: "VEGA",
      nombreCompleto: "LUIS FERNANDO OLIVERA VEGA",
      cargo: "FORMULA_PRESIDENCIAL",
      numeroCandidato: 1,
      fotoUrl: `${JNE_FOTO_BASE}/1b861ca7-3a5e-48b4-9024-08a92371e33b.jpg`,
      idOrganizacion: 18,
      estado: "INSCRITO",
      partido: "PARTIDO FRENTE DE LA ESPERANZA 2021",
    },
  },
  {
    id: 19,
    organizacion: getOrg("PARTIDO MORADO"),
    cargo: "FORMULA_PRESIDENCIAL",
    candidatos: [],
    presidente: {
      idHojaVida: 1019,
      nombres: "MESIAS ANTONIO",
      apellidoPaterno: "GUEVARA",
      apellidoMaterno: "AMASIFUEN",
      nombreCompleto: "MESIAS ANTONIO GUEVARA AMASIFUEN",
      cargo: "FORMULA_PRESIDENCIAL",
      numeroCandidato: 1,
      fotoUrl: `${JNE_FOTO_BASE}/2bd18177-d665-413d-9694-747d729d3e39.jpg`,
      idOrganizacion: 19,
      estado: "INSCRITO",
      partido: "PARTIDO MORADO",
    },
  },
  {
    id: 20,
    organizacion: getOrg("PARTIDO PAIS PARA TODOS"),
    cargo: "FORMULA_PRESIDENCIAL",
    candidatos: [],
    presidente: {
      idHojaVida: 1020,
      nombres: "CARLOS GONSALO",
      apellidoPaterno: "ALVAREZ",
      apellidoMaterno: "LOAYZA",
      nombreCompleto: "CARLOS GONSALO ALVAREZ LOAYZA",
      cargo: "FORMULA_PRESIDENCIAL",
      numeroCandidato: 1,
      fotoUrl: `${JNE_FOTO_BASE}/6ad6c5ff-0411-4ddd-9cf7-b0623f373fcf.jpg`,
      idOrganizacion: 20,
      estado: "INSCRITO",
      partido: "PARTIDO PAIS PARA TODOS",
    },
  },
  {
    id: 21,
    organizacion: getOrg("PARTIDO PATRIOTICO DEL PERU"),
    cargo: "FORMULA_PRESIDENCIAL",
    candidatos: [],
    presidente: {
      idHojaVida: 1021,
      nombres: "HERBERT",
      apellidoPaterno: "CALLER",
      apellidoMaterno: "GUTIERREZ",
      nombreCompleto: "HERBERT CALLER GUTIERREZ",
      cargo: "FORMULA_PRESIDENCIAL",
      numeroCandidato: 1,
      fotoUrl: `${JNE_FOTO_BASE}/b9db2b5c-02ff-4265-ae51-db9b1001ad70.jpg`,
      idOrganizacion: 21,
      estado: "INSCRITO",
      partido: "PARTIDO PATRIOTICO DEL PERU",
    },
  },
  {
    id: 22,
    organizacion: getOrg("PARTIDO POLITICO COOPERACION POPULAR"),
    cargo: "FORMULA_PRESIDENCIAL",
    candidatos: [],
    presidente: {
      idHojaVida: 1022,
      nombres: "YONHY",
      apellidoPaterno: "LESCANO",
      apellidoMaterno: "ANCIETA",
      nombreCompleto: "YONHY LESCANO ANCIETA",
      cargo: "FORMULA_PRESIDENCIAL",
      numeroCandidato: 1,
      fotoUrl: `${JNE_FOTO_BASE}/064360d1-ce49-4abe-939c-f4de8b0130a2.jpg`,
      idOrganizacion: 22,
      estado: "INSCRITO",
      partido: "PARTIDO POLITICO COOPERACION POPULAR",
    },
  },
  {
    id: 23,
    organizacion: getOrg("PARTIDO POLITICO INTEGRIDAD DEMOCRATICA"),
    cargo: "FORMULA_PRESIDENCIAL",
    candidatos: [],
    presidente: {
      idHojaVida: 1023,
      nombres: "WOLFGANG MARIO",
      apellidoPaterno: "GROZO",
      apellidoMaterno: "COSTA",
      nombreCompleto: "WOLFGANG MARIO GROZO COSTA",
      cargo: "FORMULA_PRESIDENCIAL",
      numeroCandidato: 1,
      fotoUrl: `${JNE_FOTO_BASE}/82ee0ff2-2336-4aba-9590-e576f7564315.jpg`,
      idOrganizacion: 23,
      estado: "INSCRITO",
      partido: "PARTIDO POLITICO INTEGRIDAD DEMOCRATICA",
    },
  },
  {
    id: 24,
    organizacion: getOrg("PARTIDO POLITICO NACIONAL PERU LIBRE"),
    cargo: "FORMULA_PRESIDENCIAL",
    candidatos: [],
    presidente: {
      idHojaVida: 1024,
      nombres: "VLADIMIR ROY",
      apellidoPaterno: "CERRON",
      apellidoMaterno: "ROJAS",
      nombreCompleto: "VLADIMIR ROY CERRON ROJAS",
      cargo: "FORMULA_PRESIDENCIAL",
      numeroCandidato: 1,
      fotoUrl: `${JNE_FOTO_BASE}/2d1bf7f2-6e88-4ea9-8ed2-975c1ae5fb92.jpg`,
      idOrganizacion: 24,
      estado: "IMPUGNADO",
      partido: "PARTIDO POLITICO NACIONAL PERU LIBRE",
    },
  },
  {
    id: 25,
    organizacion: getOrg("PARTIDO POLITICO PERU ACCION"),
    cargo: "FORMULA_PRESIDENCIAL",
    candidatos: [],
    presidente: {
      idHojaVida: 1025,
      nombres: "FRANCISCO ERNESTO",
      apellidoPaterno: "DIEZ-CANSECO",
      apellidoMaterno: "TÁVARA",
      nombreCompleto: "FRANCISCO ERNESTO DIEZ-CANSECO TÁVARA",
      cargo: "FORMULA_PRESIDENCIAL",
      numeroCandidato: 1,
      fotoUrl: `${JNE_FOTO_BASE}/ee7a080e-bc81-4c81-9e5e-9fd95ff459ab.jpg`,
      idOrganizacion: 25,
      estado: "INSCRITO",
      partido: "PARTIDO POLITICO PERU ACCION",
    },
  },
  {
    id: 26,
    organizacion: getOrg("PARTIDO POLITICO PERU PRIMERO"),
    cargo: "FORMULA_PRESIDENCIAL",
    candidatos: [],
    presidente: {
      idHojaVida: 1026,
      nombres: "MARIO ENRIQUE",
      apellidoPaterno: "VIZCARRA",
      apellidoMaterno: "CORNEJO",
      nombreCompleto: "MARIO ENRIQUE VIZCARRA CORNEJO",
      cargo: "FORMULA_PRESIDENCIAL",
      numeroCandidato: 1,
      fotoUrl: `${JNE_FOTO_BASE}/a2d0f631-fe47-4c41-92ba-7ed9f4095520.jpg`,
      idOrganizacion: 26,
      estado: "INSCRITO",
      partido: "PARTIDO POLITICO PERU PRIMERO",
    },
  },
  {
    id: 27,
    organizacion: getOrg("PARTIDO POLITICO PRIN"),
    cargo: "FORMULA_PRESIDENCIAL",
    candidatos: [],
    presidente: {
      idHojaVida: 1027,
      nombres: "WALTER GILMER",
      apellidoPaterno: "CHIRINOS",
      apellidoMaterno: "PURIZAGA",
      nombreCompleto: "WALTER GILMER CHIRINOS PURIZAGA",
      cargo: "FORMULA_PRESIDENCIAL",
      numeroCandidato: 1,
      fotoUrl: `${JNE_FOTO_BASE}/85935f77-6c46-4eab-8c7e-2494ffbcece0.jpg`,
      idOrganizacion: 27,
      estado: "INSCRITO",
      partido: "PARTIDO POLITICO PRIN",
    },
  },
  {
    id: 28,
    organizacion: getOrg("PARTIDO SICREO"),
    cargo: "FORMULA_PRESIDENCIAL",
    candidatos: [],
    presidente: {
      idHojaVida: 1028,
      nombres: "ALFONSO CARLOS",
      apellidoPaterno: "ESPA Y GARCES",
      apellidoMaterno: "ALVEAR",
      nombreCompleto: "ALFONSO CARLOS ESPA Y GARCES-ALVEAR",
      cargo: "FORMULA_PRESIDENCIAL",
      numeroCandidato: 1,
      fotoUrl: `${JNE_FOTO_BASE}/7d91e14f-4417-4d61-89ba-3e686dafaa95.jpg`,
      idOrganizacion: 28,
      estado: "INSCRITO",
      partido: "PARTIDO SICREO",
    },
  },
  {
    id: 29,
    organizacion: getOrg("PERU MODERNO"),
    cargo: "FORMULA_PRESIDENCIAL",
    candidatos: [],
    presidente: {
      idHojaVida: 1029,
      nombres: "CARLOS ERNESTO",
      apellidoPaterno: "JAICO",
      apellidoMaterno: "CARRANZA",
      nombreCompleto: "CARLOS ERNESTO JAICO CARRANZA",
      cargo: "FORMULA_PRESIDENCIAL",
      numeroCandidato: 1,
      fotoUrl: `${JNE_FOTO_BASE}/a669a883-bf8a-417c-9296-c14b943c3943.jpg`,
      idOrganizacion: 29,
      estado: "INSCRITO",
      partido: "PERU MODERNO",
    },
  },
  {
    id: 30,
    organizacion: getOrg("PODEMOS PERU"),
    cargo: "FORMULA_PRESIDENCIAL",
    candidatos: [],
    presidente: {
      idHojaVida: 1030,
      nombres: "JOSE LEON",
      apellidoPaterno: "LUNA",
      apellidoMaterno: "GALVEZ",
      nombreCompleto: "JOSE LEON LUNA GALVEZ",
      cargo: "FORMULA_PRESIDENCIAL",
      numeroCandidato: 1,
      fotoUrl: `${JNE_FOTO_BASE}/073703ca-c427-44f0-94b1-a782223a5e10.jpg`,
      idOrganizacion: 30,
      estado: "INSCRITO",
      partido: "PODEMOS PERU",
    },
  },
  {
    id: 31,
    organizacion: getOrg("PRIMERO LA GENTE - COMUNIDAD, ECOLOGIA, LIBERTAD Y PROGRESO"),
    cargo: "FORMULA_PRESIDENCIAL",
    candidatos: [],
    presidente: {
      idHojaVida: 1031,
      nombres: "MARIA SOLEDAD",
      apellidoPaterno: "PEREZ TELLO DE",
      apellidoMaterno: "RODRIGUEZ",
      nombreCompleto: "MARIA SOLEDAD PEREZ TELLO DE RODRIGUEZ",
      cargo: "FORMULA_PRESIDENCIAL",
      numeroCandidato: 1,
      fotoUrl: `${JNE_FOTO_BASE}/929e1a63-335d-4f3a-ba26-f3c7ff136213.jpg`,
      idOrganizacion: 31,
      estado: "INSCRITO",
      partido: "PRIMERO LA GENTE - COMUNIDAD, ECOLOGIA, LIBERTAD Y PROGRESO",
    },
  },
  {
    id: 32,
    organizacion: getOrg("PROGRESEMOS"),
    cargo: "FORMULA_PRESIDENCIAL",
    candidatos: [],
    presidente: {
      idHojaVida: 1032,
      nombres: "PAUL DAVIS",
      apellidoPaterno: "JAIMES",
      apellidoMaterno: "BLANCO",
      nombreCompleto: "PAUL DAVIS JAIMES BLANCO",
      cargo: "FORMULA_PRESIDENCIAL",
      numeroCandidato: 1,
      fotoUrl: `${JNE_FOTO_BASE}/b2e00ae2-1e50-4ad3-a103-71fc7e4e8255.jpg`,
      idOrganizacion: 32,
      estado: "INSCRITO",
      partido: "PROGRESEMOS",
    },
  },
  {
    id: 33,
    organizacion: getOrg("RENOVACION POPULAR"),
    cargo: "FORMULA_PRESIDENCIAL",
    candidatos: [],
    presidente: {
      idHojaVida: 1033,
      nombres: "RAFAEL BERNARDO",
      apellidoPaterno: "LOPEZ ALIAGA",
      apellidoMaterno: "CAZORLA",
      nombreCompleto: "RAFAEL BERNARDO LOPEZ ALIAGA CAZORLA",
      cargo: "FORMULA_PRESIDENCIAL",
      numeroCandidato: 1,
      fotoUrl: `${JNE_FOTO_BASE}/8e6b9124-2883-4143-8768-105f2ce780eb.jpg`,
      idOrganizacion: 33,
      estado: "INSCRITO",
      partido: "RENOVACION POPULAR",
    },
  },
  {
    id: 34,
    organizacion: getOrg("SALVEMOS AL PERU"),
    cargo: "FORMULA_PRESIDENCIAL",
    candidatos: [],
    presidente: {
      idHojaVida: 1034,
      nombres: "ANTONIO",
      apellidoPaterno: "ORTIZ",
      apellidoMaterno: "VILLANO",
      nombreCompleto: "ANTONIO ORTIZ VILLANO",
      cargo: "FORMULA_PRESIDENCIAL",
      numeroCandidato: 1,
      fotoUrl: `${JNE_FOTO_BASE}/ac0b0a59-ead5-4ef1-8ef8-8967e322d6ca.jpg`,
      idOrganizacion: 34,
      estado: "INSCRITO",
      partido: "SALVEMOS AL PERU",
    },
  },
  {
    id: 35,
    organizacion: getOrg("UN CAMINO DIFERENTE"),
    cargo: "FORMULA_PRESIDENCIAL",
    candidatos: [],
    presidente: {
      idHojaVida: 1035,
      nombres: "ROSARIO DEL PILAR",
      apellidoPaterno: "FERNANDEZ",
      apellidoMaterno: "BAZAN",
      nombreCompleto: "ROSARIO DEL PILAR FERNANDEZ BAZAN",
      cargo: "FORMULA_PRESIDENCIAL",
      numeroCandidato: 1,
      fotoUrl: `${JNE_FOTO_BASE}/5c703ce9-ba1e-4490-90bf-61006740166f.jpg`,
      idOrganizacion: 35,
      estado: "INSCRITO",
      partido: "UN CAMINO DIFERENTE",
    },
  },
  {
    id: 36,
    organizacion: getOrg("UNIDAD NACIONAL"),
    cargo: "FORMULA_PRESIDENCIAL",
    candidatos: [],
    presidente: {
      idHojaVida: 1036,
      nombres: "ROBERTO ENRIQUE",
      apellidoPaterno: "CHIABRA",
      apellidoMaterno: "LEON",
      nombreCompleto: "ROBERTO ENRIQUE CHIABRA LEON",
      cargo: "FORMULA_PRESIDENCIAL",
      numeroCandidato: 1,
      fotoUrl: `${JNE_FOTO_BASE}/ac0b0a59-ead5-4ef1-8ef8-8967e322d6ca.jpg`,
      idOrganizacion: 36,
      estado: "INSCRITO",
      partido: "UNIDAD NACIONAL",
    },
  },
];

// --- Helper para generar listas de congresistas mock ---
// Los candidatos a congreso serán cargados desde Supabase en Sprint 2

function generarListaCandidatos(
  org: OrganizacionPolitica,
  cargo: "SENADOR_NACIONAL" | "SENADOR_REGIONAL" | "DIPUTADO" | "PARLAMENTO_ANDINO",
  listaNombres: Array<{ nombres: string; apellidoPaterno: string; apellidoMaterno: string }>,
  baseId: number
) {
  return listaNombres.map((p, idx) => ({
    idHojaVida: baseId + idx,
    nombres: p.nombres,
    apellidoPaterno: p.apellidoPaterno,
    apellidoMaterno: p.apellidoMaterno,
    nombreCompleto: `${p.nombres} ${p.apellidoPaterno} ${p.apellidoMaterno}`.trim(),
    cargo,
    numeroCandidato: idx + 1,
    idOrganizacion: org.id,
    estado: "INSCRITO" as const,
    partido: org.nombre,
  }));
}

// Para el simulador educativo usamos los primeros 6 partidos más conocidos
// En Sprint 2 se reemplazarán con datos reales de Supabase
const ORGS_SIMULADOR = ORGANIZACIONES.slice(0, 6);

// --- Senadores Nacionales (simulador educativo) ---
export const SENADORES_NACIONALES: ListaElectoral[] = ORGS_SIMULADOR.map((org, orgIdx) => ({
  id: 100 + orgIdx,
  organizacion: org,
  cargo: "SENADOR_NACIONAL" as const,
  candidatos: generarListaCandidatos(
    org,
    "SENADOR_NACIONAL",
    [
      { nombres: "CANDIDATO 1", apellidoPaterno: org.sigla, apellidoMaterno: "SENADO" },
      { nombres: "CANDIDATO 2", apellidoPaterno: org.sigla, apellidoMaterno: "SENADO" },
      { nombres: "CANDIDATO 3", apellidoPaterno: org.sigla, apellidoMaterno: "SENADO" },
      { nombres: "CANDIDATO 4", apellidoPaterno: org.sigla, apellidoMaterno: "SENADO" },
      { nombres: "CANDIDATO 5", apellidoPaterno: org.sigla, apellidoMaterno: "SENADO" },
    ],
    10000 + orgIdx * 100
  ),
}));

// --- Senadores Regionales (Lima Metropolitana — 4 senadores) ---
export const SENADORES_REGIONALES: ListaElectoral[] = ORGS_SIMULADOR.map((org, orgIdx) => ({
  id: 200 + orgIdx,
  organizacion: org,
  cargo: "SENADOR_REGIONAL" as const,
  candidatos: generarListaCandidatos(
    org,
    "SENADOR_REGIONAL",
    [
      { nombres: "CANDIDATO 1", apellidoPaterno: org.sigla, apellidoMaterno: "LIMA" },
      { nombres: "CANDIDATO 2", apellidoPaterno: org.sigla, apellidoMaterno: "LIMA" },
      { nombres: "CANDIDATO 3", apellidoPaterno: org.sigla, apellidoMaterno: "LIMA" },
    ],
    20000 + orgIdx * 100
  ),
}));

// --- Diputados (Lima Metropolitana) ---
export const DIPUTADOS: ListaElectoral[] = ORGS_SIMULADOR.map((org, orgIdx) => ({
  id: 300 + orgIdx,
  organizacion: org,
  cargo: "DIPUTADO" as const,
  candidatos: generarListaCandidatos(
    org,
    "DIPUTADO",
    [
      { nombres: "CANDIDATO 1", apellidoPaterno: org.sigla, apellidoMaterno: "DIPUT" },
      { nombres: "CANDIDATO 2", apellidoPaterno: org.sigla, apellidoMaterno: "DIPUT" },
      { nombres: "CANDIDATO 3", apellidoPaterno: org.sigla, apellidoMaterno: "DIPUT" },
      { nombres: "CANDIDATO 4", apellidoPaterno: org.sigla, apellidoMaterno: "DIPUT" },
      { nombres: "CANDIDATO 5", apellidoPaterno: org.sigla, apellidoMaterno: "DIPUT" },
    ],
    30000 + orgIdx * 100
  ),
}));

// --- Parlamento Andino ---
export const PARLAMENTO_ANDINO: ListaElectoral[] = ORGS_SIMULADOR.map((org, orgIdx) => ({
  id: 400 + orgIdx,
  organizacion: org,
  cargo: "PARLAMENTO_ANDINO" as const,
  candidatos: generarListaCandidatos(
    org,
    "PARLAMENTO_ANDINO",
    [
      { nombres: "CANDIDATO 1", apellidoPaterno: org.sigla, apellidoMaterno: "ANDINO" },
      { nombres: "CANDIDATO 2", apellidoPaterno: org.sigla, apellidoMaterno: "ANDINO" },
      { nombres: "CANDIDATO 3", apellidoPaterno: org.sigla, apellidoMaterno: "ANDINO" },
    ],
    40000 + orgIdx * 100
  ),
}));

// --- Datos completos del simulador ---
export const DATOS_SIMULADOR: DatosSimulador = {
  formulasPresidenciales: FORMULAS_PRESIDENCIALES,
  senadoresNacionales: SENADORES_NACIONALES,
  senadoresRegionales: SENADORES_REGIONALES,
  diputados: DIPUTADOS,
  parlamentoAndino: PARLAMENTO_ANDINO,
};
